# Generated by Django 5.2.6 on 2026-02-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0002_studentcounseling_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcounseling',
            name='last_submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
