# Generated by Django 5.2.6 on 2026-02-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0003_studentcounseling_last_submission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20)),
                ('grievance_type', models.CharField(choices=[('Academic', 'Academic (Marks, Syllabus, etc.)'), ('Facility', 'Facilities (Infrastructure, Library, etc.)'), ('Administrative', 'Administrative (Fee, ID card, etc.)'), ('Ragging', 'Ragging / Harassment'), ('Other', 'Other')], max_length=50)),
                ('incident_date', models.DateField()),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='grievance_attachments/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('residence_hostel', models.BooleanField(default=False)),
                ('residence_days_scholar', models.BooleanField(default=False)),
                ('residence_college_bus', models.BooleanField(default=False)),
                ('residence_rtc_bus', models.BooleanField(default=False)),
                ('hostel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('room_no', models.CharField(blank=True, max_length=10, null=True)),
                ('roommate1', models.CharField(blank=True, max_length=100, null=True)),
                ('roll_no1', models.CharField(blank=True, max_length=10, null=True)),
                ('roommate2', models.CharField(blank=True, max_length=100, null=True)),
                ('roll_no2', models.CharField(blank=True, max_length=10, null=True)),
                ('roommate3', models.CharField(blank=True, max_length=100, null=True)),
                ('roll_no3', models.CharField(blank=True, max_length=10, null=True)),
                ('bus_route', models.CharField(blank=True, max_length=100, null=True)),
                ('bus_no', models.CharField(blank=True, max_length=10, null=True)),
                ('rtc_travel_place', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_details', models.CharField(blank=True, max_length=100, null=True)),
                ('day_scholar_address', models.TextField(blank=True, null=True)),
                ('ds_name1', models.CharField(blank=True, max_length=100, null=True)),
                ('ds_roll1', models.CharField(blank=True, max_length=20, null=True)),
                ('ds_name2', models.CharField(blank=True, max_length=100, null=True)),
                ('ds_roll2', models.CharField(blank=True, max_length=20, null=True)),
                ('ds_name3', models.CharField(blank=True, max_length=100, null=True)),
                ('ds_roll3', models.CharField(blank=True, max_length=20, null=True)),
                ('month1', models.CharField(blank=True, max_length=20, null=True)),
                ('classes_conducted1', models.IntegerField(blank=True, null=True)),
                ('classes_attended1', models.IntegerField(blank=True, null=True)),
                ('attendance_percent1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('monthly_letter1', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('followup1', models.TextField(blank=True, null=True)),
                ('month2', models.CharField(blank=True, max_length=20, null=True)),
                ('classes_conducted2', models.IntegerField(blank=True, null=True)),
                ('classes_attended2', models.IntegerField(blank=True, null=True)),
                ('attendance_percent2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('monthly_letter2', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('followup2', models.TextField(blank=True, null=True)),
                ('month3', models.CharField(blank=True, max_length=20, null=True)),
                ('classes_conducted3', models.IntegerField(blank=True, null=True)),
                ('classes_attended3', models.IntegerField(blank=True, null=True)),
                ('attendance_percent3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('monthly_letter3', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('followup3', models.TextField(blank=True, null=True)),
                ('month4', models.CharField(blank=True, max_length=20, null=True)),
                ('classes_conducted4', models.IntegerField(blank=True, null=True)),
                ('classes_attended4', models.IntegerField(blank=True, null=True)),
                ('attendance_percent4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('monthly_letter4', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('followup4', models.TextField(blank=True, null=True)),
                ('month5', models.CharField(blank=True, max_length=20, null=True)),
                ('classes_conducted5', models.IntegerField(blank=True, null=True)),
                ('classes_attended5', models.IntegerField(blank=True, null=True)),
                ('attendance_percent5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('monthly_letter5', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('followup5', models.TextField(blank=True, null=True)),
                ('subject1', models.CharField(blank=True, max_length=100, null=True)),
                ('mid1_1', models.IntegerField(blank=True, null=True)),
                ('mid2_1', models.IntegerField(blank=True, null=True)),
                ('sessional1', models.IntegerField(blank=True, null=True)),
                ('endsem1', models.IntegerField(blank=True, null=True)),
                ('total1', models.IntegerField(blank=True, null=True)),
                ('result1', models.CharField(blank=True, choices=[('P', 'Pass'), ('F', 'Fail')], max_length=1, null=True)),
                ('pass_year1', models.CharField(blank=True, max_length=4, null=True)),
                ('subject2', models.CharField(blank=True, max_length=100, null=True)),
                ('mid1_2', models.IntegerField(blank=True, null=True)),
                ('mid2_2', models.IntegerField(blank=True, null=True)),
                ('sessional2', models.IntegerField(blank=True, null=True)),
                ('endsem2', models.IntegerField(blank=True, null=True)),
                ('total2', models.IntegerField(blank=True, null=True)),
                ('result2', models.CharField(blank=True, choices=[('P', 'Pass'), ('F', 'Fail')], max_length=1, null=True)),
                ('pass_year2', models.CharField(blank=True, max_length=4, null=True)),
                ('subject3', models.CharField(blank=True, max_length=100, null=True)),
                ('mid1_3', models.IntegerField(blank=True, null=True)),
                ('mid2_3', models.IntegerField(blank=True, null=True)),
                ('sessional3', models.IntegerField(blank=True, null=True)),
                ('endsem3', models.IntegerField(blank=True, null=True)),
                ('total3', models.IntegerField(blank=True, null=True)),
                ('result3', models.CharField(blank=True, choices=[('P', 'Pass'), ('F', 'Fail')], max_length=1, null=True)),
                ('pass_year3', models.CharField(blank=True, max_length=4, null=True)),
                ('subject4', models.CharField(blank=True, max_length=100, null=True)),
                ('mid1_4', models.IntegerField(blank=True, null=True)),
                ('mid2_4', models.IntegerField(blank=True, null=True)),
                ('sessional4', models.IntegerField(blank=True, null=True)),
                ('endsem4', models.IntegerField(blank=True, null=True)),
                ('total4', models.IntegerField(blank=True, null=True)),
                ('result4', models.CharField(blank=True, choices=[('P', 'Pass'), ('F', 'Fail')], max_length=1, null=True)),
                ('pass_year4', models.CharField(blank=True, max_length=4, null=True)),
                ('subject5', models.CharField(blank=True, max_length=100, null=True)),
                ('mid1_5', models.IntegerField(blank=True, null=True)),
                ('mid2_5', models.IntegerField(blank=True, null=True)),
                ('sessional5', models.IntegerField(blank=True, null=True)),
                ('endsem5', models.IntegerField(blank=True, null=True)),
                ('total5', models.IntegerField(blank=True, null=True)),
                ('result5', models.CharField(blank=True, choices=[('P', 'Pass'), ('F', 'Fail')], max_length=1, null=True)),
                ('pass_year5', models.CharField(blank=True, max_length=4, null=True)),
                ('counseling_date1', models.CharField(blank=True, max_length=100, null=True)),
                ('counseling_description1', models.TextField(blank=True, null=True)),
                ('prizes_participations1', models.TextField(blank=True, null=True)),
                ('prizes_participations2', models.TextField(blank=True, null=True)),
                ('counseling_date4', models.CharField(blank=True, max_length=100, null=True)),
                ('prizes_participations3', models.TextField(blank=True, null=True)),
                ('counseling_date2', models.CharField(blank=True, max_length=100, null=True)),
                ('prizes_participations4', models.TextField(blank=True, null=True)),
                ('counseling_date3', models.CharField(blank=True, max_length=100, null=True)),
                ('prizes_participations5', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='attendance_percent1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='attendance_percent2',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='attendance_percent3',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='attendance_percent4',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='attendance_percent5',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='bus_no',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='bus_route',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='classes_attended1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='classes_attended2',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='classes_attended3',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='classes_attended4',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='classes_attended5',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='classes_conducted1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='classes_conducted2',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='classes_conducted3',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='classes_conducted4',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='classes_conducted5',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='counseling_date1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='counseling_date2',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='counseling_date3',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='counseling_date4',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='counseling_description1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='day_scholar_address',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='ds_name1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='ds_name2',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='ds_name3',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='ds_roll1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='ds_roll2',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='ds_roll3',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='endsem1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='endsem2',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='endsem3',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='endsem4',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='endsem5',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='followup1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='followup2',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='followup3',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='followup4',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='followup5',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='hostel_name',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='mid1_1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='mid1_2',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='mid1_3',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='mid1_4',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='mid1_5',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='mid2_1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='mid2_2',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='mid2_3',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='mid2_4',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='mid2_5',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='month1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='month2',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='month3',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='month4',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='month5',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='monthly_letter1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='monthly_letter2',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='monthly_letter3',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='monthly_letter4',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='monthly_letter5',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='pass_year1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='pass_year2',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='pass_year3',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='pass_year4',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='pass_year5',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='prizes_participations1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='prizes_participations2',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='prizes_participations3',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='prizes_participations4',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='prizes_participations5',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='residence_college_bus',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='residence_days_scholar',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='residence_hostel',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='residence_rtc_bus',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='result1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='result2',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='result3',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='result4',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='result5',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='roll_no1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='roll_no2',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='roll_no3',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='room_no',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='roommate1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='roommate2',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='roommate3',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='rtc_travel_place',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='sessional1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='sessional2',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='sessional3',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='sessional4',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='sessional5',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='subject1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='subject2',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='subject3',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='subject4',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='subject5',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='total1',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='total2',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='total3',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='total4',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='total5',
        ),
        migrations.RemoveField(
            model_name='studentcounseling',
            name='vehicle_details',
        ),
    ]
