# Generated by Django 5.2.6 on 2026-02-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0005_grievance_reply_grievance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='counseling_date5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
