# Generated by Django 5.2.6 on 2026-02-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0006_grievance_counseling_date5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='attendance_percent1',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='attendance_percent2',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='attendance_percent3',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='attendance_percent4',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='attendance_percent5',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='bus_no',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='bus_route',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='classes_attended1',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='classes_attended2',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='classes_attended3',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='classes_attended4',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='classes_attended5',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='classes_conducted1',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='classes_conducted2',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='classes_conducted3',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='classes_conducted4',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='classes_conducted5',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='counseling_date1',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='counseling_date2',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='counseling_date3',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='counseling_date4',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='counseling_date5',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='counseling_description1',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='day_scholar_address',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='ds_name1',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='ds_name2',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='ds_name3',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='ds_roll1',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='ds_roll2',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='ds_roll3',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='endsem1',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='endsem2',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='endsem3',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='endsem4',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='endsem5',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='followup1',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='followup2',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='followup3',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='followup4',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='followup5',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='hostel_name',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='mid1_1',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='mid1_2',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='mid1_3',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='mid1_4',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='mid1_5',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='mid2_1',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='mid2_2',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='mid2_3',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='mid2_4',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='mid2_5',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='month1',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='month2',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='month3',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='month4',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='month5',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='monthly_letter1',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='monthly_letter2',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='monthly_letter3',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='monthly_letter4',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='monthly_letter5',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='pass_year1',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='pass_year2',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='pass_year3',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='pass_year4',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='pass_year5',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='prizes_participations1',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='prizes_participations2',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='prizes_participations3',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='prizes_participations4',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='prizes_participations5',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='residence_college_bus',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='residence_days_scholar',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='residence_hostel',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='residence_rtc_bus',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='result1',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='result2',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='result3',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='result4',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='result5',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='roll_no1',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='roll_no2',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='roll_no3',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='room_no',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='roommate1',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='roommate2',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='roommate3',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='rtc_travel_place',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='sessional1',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='sessional2',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='sessional3',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='sessional4',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='sessional5',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='subject1',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='subject2',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='subject3',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='subject4',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='subject5',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='total1',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='total2',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='total3',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='total4',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='total5',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='vehicle_details',
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='attendance_percent1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='attendance_percent2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='attendance_percent3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='attendance_percent4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='attendance_percent5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='bus_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='bus_route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='classes_attended1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='classes_attended2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='classes_attended3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='classes_attended4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='classes_attended5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='classes_conducted1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='classes_conducted2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='classes_conducted3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='classes_conducted4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='classes_conducted5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='counseling_date1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='counseling_date2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='counseling_date3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='counseling_date4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='counseling_date5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='counseling_description1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='day_scholar_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='ds_name1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='ds_name2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='ds_name3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='ds_roll1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='ds_roll2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='ds_roll3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='endsem1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='endsem2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='endsem3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='endsem4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='endsem5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='followup1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='followup2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='followup3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='followup4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='followup5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='hostel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='mid1_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='mid1_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='mid1_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='mid1_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='mid1_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='mid2_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='mid2_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='mid2_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='mid2_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='mid2_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='month1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='month2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='month3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='month4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='month5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='monthly_letter1',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='monthly_letter2',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='monthly_letter3',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='monthly_letter4',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='monthly_letter5',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='pass_year1',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='pass_year2',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='pass_year3',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='pass_year4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='pass_year5',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='prizes_participations1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='prizes_participations2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='prizes_participations3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='prizes_participations4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='prizes_participations5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='residence_college_bus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='residence_days_scholar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='residence_hostel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='residence_rtc_bus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='result1',
            field=models.CharField(blank=True, choices=[('P', 'Pass'), ('F', 'Fail')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='result2',
            field=models.CharField(blank=True, choices=[('P', 'Pass'), ('F', 'Fail')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='result3',
            field=models.CharField(blank=True, choices=[('P', 'Pass'), ('F', 'Fail')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='result4',
            field=models.CharField(blank=True, choices=[('P', 'Pass'), ('F', 'Fail')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='result5',
            field=models.CharField(blank=True, choices=[('P', 'Pass'), ('F', 'Fail')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='roll_no1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='roll_no2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='roll_no3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='room_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='roommate1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='roommate2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='roommate3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='rtc_travel_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='sessional1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='sessional2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='sessional3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='sessional4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='sessional5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='subject1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='subject2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='subject3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='subject4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='subject5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='total1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='total2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='total3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='total4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='total5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='vehicle_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
