# Generated by Django 5.2.6 on 2026-02-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0007_remove_grievance_attendance_percent1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcounseling',
            name='attendance_percent1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Attendance %'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='attendance_percent2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Attendance %'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='attendance_percent3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Attendance %'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='attendance_percent4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Attendance %'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='attendance_percent5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Attendance %'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='classes_attended1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Classes Attended'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='classes_attended2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Classes Attended'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='classes_attended3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Classes Attended'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='classes_attended4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Classes Attended'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='classes_attended5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Classes Attended'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='classes_conducted1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Classes Conducted'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='classes_conducted2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Classes Conducted'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='classes_conducted3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Classes Conducted'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='classes_conducted4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Classes Conducted'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='classes_conducted5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Classes Conducted'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='counseling_date1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Counseling Date'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='counseling_date2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Counseling Date'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='counseling_date3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Counseling Date'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='counseling_date4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Counseling Date'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='counseling_date5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Counseling Date'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='counseling_description1',
            field=models.TextField(blank=True, null=True, verbose_name='Counseling Description'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='day_scholar_address',
            field=models.TextField(blank=True, null=True, verbose_name='Day Scholar Address'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='ds_name1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DS Name 1'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='ds_name2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DS Name 2'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='ds_name3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DS Name 3'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='ds_roll1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DS Roll 1'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='ds_roll2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DS Roll 2'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='ds_roll3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DS Roll 3'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='endsem1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Endsem'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='endsem2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Endsem'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='endsem3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Endsem'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='endsem4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Endsem'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='endsem5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Endsem'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='followup1',
            field=models.TextField(blank=True, null=True, verbose_name='Follow-up'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='followup2',
            field=models.TextField(blank=True, null=True, verbose_name='Follow-up'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='followup3',
            field=models.TextField(blank=True, null=True, verbose_name='Follow-up'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='followup4',
            field=models.TextField(blank=True, null=True, verbose_name='Follow-up'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='followup5',
            field=models.TextField(blank=True, null=True, verbose_name='Follow-up'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='mid1_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mid 1'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='mid1_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mid 1'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='mid1_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mid 1'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='mid1_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mid 1'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='mid1_5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mid 1'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='mid2_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mid 2'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='mid2_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mid 2'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='mid2_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mid 2'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='mid2_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mid 2'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='mid2_5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mid 2'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='month1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='month2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='month3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='month4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='month5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='monthly_letter1',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Monthly Letter'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='monthly_letter2',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Monthly Letter'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='monthly_letter3',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Monthly Letter'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='monthly_letter4',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Monthly Letter'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='monthly_letter5',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Monthly Letter'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='pass_year1',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Pass Year'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='pass_year2',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Pass Year'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='pass_year3',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Pass Year'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='pass_year4',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Pass Year'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='pass_year5',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Pass Year'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='prizes_participations1',
            field=models.TextField(blank=True, null=True, verbose_name='Prizes & Participations'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='prizes_participations2',
            field=models.TextField(blank=True, null=True, verbose_name='Prizes & Participations'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='prizes_participations3',
            field=models.TextField(blank=True, null=True, verbose_name='Prizes & Participations'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='prizes_participations4',
            field=models.TextField(blank=True, null=True, verbose_name='Prizes & Participations'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='prizes_participations5',
            field=models.TextField(blank=True, null=True, verbose_name='Prizes & Participations'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='result1',
            field=models.CharField(blank=True, choices=[('P', 'Pass'), ('F', 'Fail')], max_length=1, null=True, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='result2',
            field=models.CharField(blank=True, choices=[('P', 'Pass'), ('F', 'Fail')], max_length=1, null=True, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='result3',
            field=models.CharField(blank=True, choices=[('P', 'Pass'), ('F', 'Fail')], max_length=1, null=True, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='result4',
            field=models.CharField(blank=True, choices=[('P', 'Pass'), ('F', 'Fail')], max_length=1, null=True, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='result5',
            field=models.CharField(blank=True, choices=[('P', 'Pass'), ('F', 'Fail')], max_length=1, null=True, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='roll_no1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Roll No 1'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='roll_no2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Roll No 2'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='roll_no3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Roll No 3'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='roommate1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Roommate 1'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='roommate2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Roommate 2'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='roommate3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Roommate 3'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='sessional1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sessional'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='sessional2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sessional'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='sessional3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sessional'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='sessional4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sessional'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='sessional5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sessional'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='subject1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='subject2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='subject3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='subject4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='subject5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='total1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='total2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='total3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='total4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='studentcounseling',
            name='total5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total'),
        ),
    ]
